sudo: required

services:
  - docker

env:
  - CROSS_TRIPLE=x86_64-linux-gnu
  - CROSS_TRIPLE=aarch64-linux-gnu

script:
  - make source
  - make copyconfig
  - make CROSS_TRIPLE=$CROSS_TRIPLE build
  - make clean
