sudo: required
services:
- docker
language: c
env:
- CROSS_TRIPLE=x86_64-linux-gnu
- CROSS_TRIPLE=arm-linux-gnueabi
- CROSS_TRIPLE=arm-linux-gnueabihf
- CROSS_TRIPLE=aarch64-linux-gnu
- CROSS_TRIPLE=powerpc64le-linux-gnu
install:
- sudo apt-get -q update && sudo apt-get -y install upx-ucl
script:
- make source
- make copyconfig
- make register
- make CROSS_TRIPLE=$CROSS_TRIPLE build
deploy:
  provider: releases
  api_key:
    secure: a1/th8l8twgJ0YdnX3EVXMmYsZdY6ZL0El4e2RihTwFYY2zXP4Uy/kZ/T8lBv3R4/Q3CkEUQhCi3xZvqQsSziA6DDMHGaDRgsuB/M8thXMD+krMACN7npc3OabaNnz2f6M5JZUWR1Nmp1rqv2PJnARvFUH6wxMwQ3+OX4SRlye5tsfcoZZ3JLtBamZe0RliiWsHgI6m2HZca863+LkxJ+VfwUqGUHNkJ87C6XPpXf8IFWLBR6BkFCL2seaUpwZt6mnTPCPiJ49ls+l3pwfp9MT1QOOEauLHrbv14zvk56e9/A/ZVJ4fADpMtZ93dp1CaKmXgfkVPtLJWCfF22vBBEiqNS74xQUX8ssum0pBJ9z8m3ed8frWc/7HHD85or6B3J8ba35OQ0nLQjb80qiq3Y5NoxfrnavE02W9rejq0TlbKnR9XYUoHWUgIX7Bf1XV41ikHQ/7Sk+Qg+wPSFCP2Fio8/612pzgJHh9aLhvhkpDyinNJPmnnReim1Zzdmtur6/XylcP4k6FrAXoiae7SmD1vh5uAm2a7lY71c9h4pIKDM4SFkbCB4WxQdbk28T2lTevWIDuUfiKFJG0zCK/nnfzGXjhtAkhgBVAA5OjYJETBy/3u56OpxHN3EgibInJCuO/MX7BkMjcacHsMX7240tJ6dBAp/YYE+LKUepCd0XA=
  file: busybox-$CROSS_TRIPLE
  on:
    repo: nlm/busybox-static-multiarch
    tags: true
  skip_cleanup: true
  overwrite: true
